-- MySQL Script generated by MySQL Workbench
-- Thu Mar 25 16:34:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desafio2IGTI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desafio2IGTI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio2IGTI` DEFAULT CHARACTER SET utf8 ;
USE `desafio2IGTI` ;

-- -----------------------------------------------------
-- Table `desafio2IGTI`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio2IGTI`.`pais` (
  `cod_pais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_pais`),
  UNIQUE INDEX `nome_pais_UNIQUE` (`nome_pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio2IGTI`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio2IGTI`.`jogo` (
  `cod_jogo` INT NOT NULL AUTO_INCREMENT,
  `nome_jogo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_jogo`),
  UNIQUE INDEX `nome_jogo_UNIQUE` (`nome_jogo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio2IGTI`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio2IGTI`.`jogador` (
  `cod_jogador` INT NOT NULL AUTO_INCREMENT,
  `nome_jogador` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `num_vitorias` INT NOT NULL,
  `num_derrotas` INT NOT NULL,
  `total_partidas` INT NOT NULL,
  `cod_pais` INT NOT NULL,
  `jcod_jogo` INT NOT NULL,
  PRIMARY KEY (`cod_jogador`),
  UNIQUE INDEX `nome_jogador_UNIQUE` (`nome_jogador` ASC) VISIBLE,
  INDEX `fk_jogador_pais_idx` (`cod_pais` ASC) VISIBLE,
  INDEX `fk_jogador_jogo1_idx` (`jcod_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_jogador_pais`
    FOREIGN KEY (`cod_pais`)
    REFERENCES `desafio2IGTI`.`pais` (`cod_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogador_jogo1`
    FOREIGN KEY (`jcod_jogo`)
    REFERENCES `desafio2IGTI`.`jogo` (`cod_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
